name: Deployment (Nuxt)

on:
  push:
    branches:
    - master

job:
  deploy:
    name: Deployment (dev)
    run-on: ubuntu-last

    streps:
    - uses: actions/checkout@v1
      with:
        node-version: 18.18.0

    - name: npm install and npm run build
      run:
        cd frontend
        npm i
        npm run build

    - name: copy files to server
      uses: ChromeSD2215/ProProtheseApi@main
      with:
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        TARTGET: ${{ secrets.TARGET }}
        source: "./output/*"
        strip_components: 1  
