name: Deployment (Stage)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deployment (Stage)
    runs-on: ubuntu-latest 

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v1
        with:
          node-version: 18.18.2    

      - name: Setup ENV's
        env:
          MAILHOST: ${{ env.MAILHOST }}
          MAILPORT: ${{ env.MAILPORT }}
          MAILUSER: ${{ env.MAILUSER }}
          MAILPASS: ${{ env.MAILPASS }}
          CONTACTMAIL: ${{ env.CONTACTMAIL }}
          NOREPLY: ${{ env.NOREPLY }}
          STRAPI_URL: ${{ env.STRAPI_URL }}
          BETTERUPTIMETOKEN: ${{env.BETTERUPTIMETOKEN}}
          BETTERUPTIMEPAGES: ${{env.BETTERUPTIMEPAGES}}
          NUXT_PUBLIC_SITE_URL: ${{ env.NUXT_PUBLIC_SITE_URL }}
        run: echo "Tell me MAILHOST ${{env.BETTERUPTIMETOKEN}}"

      - name: Tell me env
        run: echo "Tell me MAILHOST ${{env.BETTERUPTIMETOKEN}} - ${{vars.BETTERUPTIMETOKEN}}"

      - name: Tell me secret
        run: echo "Tell me MAILHOST ${{ secrets.MAILHOST }}"

      #- name: Build Node
      #  run: | 
      #    cd frontend
      #    npm i
      #    npm run start:frontend:build
