name: Deployment (Github Pages)

on:
  push:
    branches:
      - test 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest 

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v1
        with:
          node-version: 18.18.2  

      - name: Setup ENV's
        env:
          MAILHOST: ${{ vars.MAILHOST }}
          MAILPORT: ${{ vars.MAILPORT }}
          MAILUSER: ${{ vars.MAILUSER }}
          MAILPASS: ${{ vars.MAILPASS }}
          CONTACTMAIL: ${{ vars.CONTACTMAIL }}
          NOREPLY: ${{ vars.NOREPLY }}
          STRAPI_URL: ${{ vars.STRAPI_URL }}
          BETTERUPTIMETOKEN: ${{vars.BETTERUPTIMETOKEN}}
          BETTERUPTIMEPAGES: ${{vars.BETTERUPTIMEPAGES}}
          NUXT_PUBLIC_SITE_URL: ${{ vars.NUXT_PUBLIC_SITE_URL }}
          run: ls -al

      - name: Build Nuxt.js
        run: |
          cd frontend
          npm i
          npm run generate --preset=github_pages
          echo "Debug Directory Structure"
          ls -R

