name: Deployment (Stage)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deployment (Stage)
    runs-on: ubuntu-latest 

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v1
        with:
          node-version: 18.18.2    

      - name: Build Node
        run: | 
          cd frontend
          npm i
          npm run build
