name: Deployment (Nuxt)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deployment (dev)
    runs-on: ubuntu-latest 

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v1
        with:
          node-version: 18.18.2

      - name: npm install and npm run build
        run: |
          cd frontend
          npm i
          npm run build

      - name: Copy files to server
        uses: ChromeSD22159/ProProtheseApi@main
        with:
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TARGET: ${{ secrets.TARGET }} 
          source: "./output/*"
          strip_components: 1