name: Deployment (Stage)

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Deployment (Stage)
    runs-on: ubuntu-latest 

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v1
        with:
          node-version: 18.18.2    

      - name: Setup ENV's
        env:
          MAILHOST: ${{ vars.MAILHOST }}
          MAILPORT: ${{ vars.MAILPORT }}
          MAILUSER: ${{ vars.MAILUSER }}
          MAILPASS: ${{ vars.MAILPASS }}
          CONTACTMAIL: ${{ vars.CONTACTMAIL }}
          NOREPLY: ${{ vars.NOREPLY }}
          STRAPI_URL: ${{ vars.STRAPI_URL }}
          BETTERUPTIMETOKEN: ${{vars.BETTERUPTIMETOKEN}}
          BETTERUPTIMEPAGES: ${{vars.BETTERUPTIMEPAGES}}
          NUXT_PUBLIC_SITE_URL: ${{ vars.NUXT_PUBLIC_SITE_URL }}
        run: |
            echo "Token: ${{ secrets.ACCESS_TOKEN }} " 
            cd frontend
            npm i
            npm run generate
            ls -al .output/public
            pwd 

  print-path:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Print current directory
        run: pwd 

      - name: Print contents of .output/public
        run: |
          cd frontend
          ls -al frontend/.output/public || true
          pwd 

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write 

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      steps:
      - name: Print current directory
        run: pwd 



  