name: Deployment (Stage)

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Deployment (Stage)
    runs-on: ubuntu-latest 

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v1
        with:
          node-version: 18.18.2    

      - name: Setup ENV's
        env:
          MAILHOST: ${{ vars.MAILHOST }}
          MAILPORT: ${{ vars.MAILPORT }}
          MAILUSER: ${{ vars.MAILUSER }}
          MAILPASS: ${{ vars.MAILPASS }}
          CONTACTMAIL: ${{ vars.CONTACTMAIL }}
          NOREPLY: ${{ vars.NOREPLY }}
          STRAPI_URL: ${{ vars.STRAPI_URL }}
          BETTERUPTIMETOKEN: ${{vars.BETTERUPTIMETOKEN}}
          BETTERUPTIMEPAGES: ${{vars.BETTERUPTIMEPAGES}}
          NUXT_PUBLIC_SITE_URL: ${{ vars.NUXT_PUBLIC_SITE_URL }}
        run: |
            echo "Token: ${{ secrets.ACCESS_TOKEN }} " 
            cd frontend
            npm i
            npm run generate
            ls -al .output/public
            pwd 
        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages .
          #folder: /home/runner/work/ProProtheseApi/ProProtheseApi/frontend/.output/public
           folder: frontend/.output/public
          token: ${{ secrets.ACCESS_TOKEN }}
          clean: true

  print-path:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Print current directory
        run: |
          cd frontend
          pwd