name: Deployment (Stage)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deployment (Stage)
    runs-on: ubuntu-latest 

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v1
        with:
          node-version: 18.18.2    

      - name: Build Node
        env:
          MAILHOST=${{USERNAME}}
          MAILPORT=${{USERNAME}}
          MAILUSER=noprely@frederikkohler.de
          MAILPASS=noReply@Fr3d3rik@Kohler
          CONTACTMAIL=info@frederikkohler.de
          NOREPLY=noprely@frederikkohler.de
          STRAPI_URL=https://api.frederikkohler.de/
          BETTERUPTIMETOKEN=GX6j3RWh5z33YETb4CnjTPRx
          BETTERUPTIMEPAGES=["174778"]
          NUXT_PUBLIC_SITE_URL=https://www.frederikkohler.de/
        run: echo "${{USERNAME}}"
        run: | 
          cd frontend
          npm i
          npm run start:frontend:build
