name: Deployment (Stage)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deployment (Stage)
    runs-on: ubuntu-latest 

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v1
        with:
          node-version: 18.18.2    

      - name: Setup ENV's
        env:
          MAILHOST: ${{ vars.MAILHOST }}
          MAILPORT: ${{ vars.MAILPORT }}
          MAILUSER: ${{ vars.MAILUSER }}
          MAILPASS: ${{ vars.MAILPASS }}
          CONTACTMAIL: ${{ vars.CONTACTMAIL }}
          NOREPLY: ${{ vars.NOREPLY }}
          STRAPI_URL: ${{ vars.STRAPI_URL }}
          BETTERUPTIMETOKEN: ${{vars.BETTERUPTIMETOKEN}}
          BETTERUPTIMEPAGES: ${{vars.BETTERUPTIMEPAGES}}
          NUXT_PUBLIC_SITE_URL: ${{ vars.NUXT_PUBLIC_SITE_URL }}
        run: |
            echo "Tell me ${{ vars.STRAPI_URL }} ${{vars.BETTERUPTIMETOKEN}} ${{vars.NOREPLY}}" 
            cd frontend
            npm i
            npm run generate
            echo "Debug Directory Structure"
            ls -R
            echo "Work Directory Structure"
             run: ls -al

            #https://fullstackjack.dev/articles/deploy-nuxt3-github-actions