name: Deployment (Nuxt)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deployment (dev)
    runs-on: ubuntu-latest  # Schreibfehler: 'ubuntu-last' sollte 'ubuntu-latest' sein

    steps:  # Schreibfehler: 'streps' sollte 'steps' sein
      - name: Checkout Repository
        uses: actions/checkout@v1
        with:
          node-version: 18.18.0

      - name: npm install and npm run build
        run: |
          cd frontend
          npm i
          npm run build

      - name: Copy files to server
        uses: ChromeSD2215/ProProtheseApi@main
        with:
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TARGET: ${{ secrets.TARGET }}  # Schreibfehler: 'TARTGET' sollte 'TARGET' sein
          source: "./output/*"
          strip_components: 1